object Versions {
    const val agpVersion = "8.2.0"
    const val kotlinVersion = "1.9.10"
    const val splashVersion = "1.0.1"
    const val hiltVersion = "2.48.1"
    const val lifecycleVersion = "2.6.2"
    const val navigationVersion = "2.7.6"
    const val glideVersion = "4.16.0"
    const val okhttpVersion = "4.10.0"
    const val retrofitVersion = "2.9.0"
    const val secretsGradleVersion = "2.0.1"
    const val googleServicesVersion = "4.3.15"
    const val roomVersion = "2.6.1"
    const val pagingVersion = "3.2.1"
    const val shimmerVersion = "0.5.0"
    const val swipeVersion = "1.1.0"
    const val lottieVersion = "6.0.0"
}